// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jquaayoqnomtxbfmacpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxdWFheW9xbm9tdHhiZm1hY3B5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNzI3NjgsImV4cCI6MjA1Njc0ODc2OH0.LuoZdyA0qniXZlt_jb8dsMrZoXkVkzwax6eEMnEA4TU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);